name: "Run Hammering"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:      
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v8
        with:
          name: nixpkgs-hammering-action
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      
      - name: Modify nixpkgs
        run: |
          # Clone nixpkgs
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"

          git clone https://github.com/NixOS/nixpkgs.git --branch master --single-branch /tmp/nixpkgs --depth 1 --quiet
          
          # Make a change
          sed -i 's/maintainers/#maintainers/' /tmp/nixpkgs/pkgs/development/python-modules/numpy/default.nix

          (cd /tmp/nixpkgs && git commit -am "Look ma, I changed python3Packages.numpy")

      - uses: ./
        with:
          nixpkgs_path: /tmp/nixpkgs
          token: ${{ secrets.GITHUB_TOKEN }}
          post_check: false